#define MOUSEKEY_DELAY		200
#define MOUSEKEY_INTERVAL	40
#define MOUSEKEY_MAX_SPEED	7
#define MOUSEKEY_TIME_TO_MAX	12
#define TAPPING_TERM        200
#define BACKLIGHT_BREATHING
#define BACKLIGHT_PIRIOD 12
